import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider";
import MyNav from "@/components/MyNav";
import { Toaster } from "sonner";
import InternetGate from "@/components/deteksiInternet";

export const nexusBold = localFont({
  src: [
    {
      path: '../assets/fonts/nexus/Nexusbold Regular.otf',
      style: 'normal',
    },
    {
      path: '../assets/fonts/nexus/Nexusbold Regularitalic.otf',
      style: 'italic',
    },
    {
      path: '../assets/fonts/nexus/Nexusbold Roundeditalic.otf',
      style: 'text-rounded italic',
    },
    {
      path: '../assets/fonts/nexus/Nexusbold Rounded.otf',
      style: 'text-rounded',
    },
  ],
})
export const sterion = localFont({
  src: [
    {
      path: '../assets/fonts/sterion/Sterion-BLLld.ttf',
      style: 'normal',
    },
    {
      path: '../assets/fonts/sterion/SterionItalic-R99PA.ttf',
      style: 'italic',
    },
  ],
})

export const AudioWide = localFont({
  src:[
    {
      path: '../assets/fonts/Audiowide/AudioWide-Regular.ttf',
    }
  ]
});
export const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-orbitron",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}   antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <MyNav />
            <InternetGate>
              
              <Toaster />
              {children}
            </InternetGate>
          </ThemeProvider>
      </body>
    </html>
  );
}
